
trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Sonarcloud'
    organization: 'moerwald-github'
    scannerMode: 'MSBuild'
    projectKey: 'moerwald_TplDataflow.Extension'
    projectName: 'TplDataflow.Extension'

# Install SonarScanner
- script: |
     dotnet tool install --global dotnet-sonarscanner
  displayName: 'install sonarscanner'
  
# Run Sonar
- script: |
     dotnet sonarscanner begin /k:"moerwald_TplDataflow.Extension" 
  displayName: 'sonarscanner begin'


- script: |
    dotnet build --configuration $(buildConfiguration) -v d
  displayName: 'dotnet build $(buildConfiguration)'
- script: |
    dotnet pack --configuration $(buildConfiguration)
  displayName: 'dotnet pack $(buildConfiguration)'
- script: |
    mkdir $(Build.SourcesDirectory)\results
    dotnet test --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura  
    copy TplDataflow.Extension.Tests\coverage.cobertura.xml $(Build.SourcesDirectory)\results
    dotnet tool install dotnet-reportgenerator-globaltool --tool-path . --version 4.0.0-rc4
    .\reportgenerator "-reports:$(Build.SourcesDirectory)\results\coverage.cobertura.xml" "-targetdir:$(Build.SourcesDirectory)\results" "-reporttypes:HTMLInline;HTMLChart"
  displayName: 'Unit testing'
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
- task: PublishCodeCoverageResults@1
  inputs:
    summaryFileLocation: $(Build.SourcesDirectory)\results\coverage.cobertura.xml
    reportDirectory: $(Build.SourcesDirectory)\results
    codecoverageTool: cobertura

# End SonarScanner
- script: |
    dotnet sonarscanner end 
  displayName: 'sonarscanner end'

    
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
    
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    projects: TplDataFlow.Extension\TplDataFlow.Extension.csproj
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: true

- task: PublishBuildArtifacts@1




